# -*- coding: utf-8 -*-
"""circle_radius_finder.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JfvZ6UulR5L8C8CScUdS4iIQIqKpBtqg
"""

r = int(input('enter the radius of the circle'))
temp = 3.14*r*r
print("the area of the circle for given radius is :",temp)

