# -*- coding: utf-8 -*-
"""circle*radius*finder.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EyWwbOiBU7eICH8smBjlP0RDhBRKC-Bq
"""

r = int(input("Input the radius of the circle "))
a = 3.14*r*r
print("The area of the circle with radius",r,"is",a)