# -*- coding: utf-8 -*-
"""file_extension_finder.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JfvZ6UulR5L8C8CScUdS4iIQIqKpBtqg
"""

a = str(input('enter the file name with extension'))
if a.endswith('.py'):
  print('the extension is PYTHON')
elif a.endswith('.txt'):
  print('the extension is TEXT')
elif a.endswith('.cpp'):
  print('the extension is CPP')
elif a.endswith('.pl'):
  print('the extension is PERL')
else:
  print('please enter a valid file extension')