# -*- coding: utf-8 -*-
"""file*extension*finder.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EyWwbOiBU7eICH8smBjlP0RDhBRKC-Bq
"""

a = str(input("enter th file-name with extension "))
if a.endswith(".py"):
  print("The extension is PYTHON")
elif a.endswith(".txt"):
  print("The extension of the given file is TEXT")
elif a.endswith(".cpp"):
  print("The extension of the given file is C++")
elif a.endswith(".pl"):
  print("The extension of the given file is PERL")
else:
  print("please enter a valid file extension")